#!/bin/bash
# This is a comment
sed 's/Blockly./ScratchBlocks./g' ./arduino_compressed.js >> myfile1_1
sed 's/Blockly./ScratchBlocks./g' ./blocks_compressed.js >> myfile2_1
sed 's/Blockly./ScratchBlocks./g' ./blockly_compressed.js >> myfile3_1

sed 's/ScratchBlocks.Arduino./Blockly.Arduino./g' ./myfile1_1 >> myfile1_2
sed 's/ScratchBlocks.Arduino./Blockly.Arduino./g' ./myfile2_1 >> myfile2_2
sed 's/ScratchBlocks.Arduino./Blockly.Arduino./g' ./myfile3_1 >> myfile3_2

sed '2a\import ScratchBlocks from "scratch-blocks";' ./myfile1_2 >> myfile1_3

rm arduino_compressed.js
rm blocks_compressed.js
rm blockly_compressed.js
rm myfile1_1
rm myfile2_1
rm myfile3_1
rm myfile1_2

mv -f myfile1_3 arduino_compressed.js
mv -f myfile2_2 blocks_compressed.js
mv -f myfile3_2 blockly_compressed.js


